version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - qdrant
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL:-text-embedding-3-large}
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION: ${QDRANT_COLLECTION:-company_knowledge}
    ports:
      - "5088:8080"

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VITE_API_BASE: http://api:8080
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  qdrant_storage:
